"""Utilities for loading checkpoints generated by FedFairLab."""

import torch


def load_trusted_checkpoint(path, map_location="cpu"):
    """
    Load a checkpoint produced by this project.

    PyTorch 2.6 changed ``torch.load`` to default to ``weights_only=True``.
    FedFairLab checkpoints intentionally contain full Python dictionaries with
    model parameters, metrics and occasionally NumPy scalar values. Those files
    therefore need regular pickle loading. Only use this helper for local
    checkpoints generated by a trusted FedFairLab run.

    Args:
        path: Filesystem path of the checkpoint.
        map_location: Device remapping passed to ``torch.load``.

    Returns:
        Deserialized checkpoint object.
    """
    return torch.load(path, map_location=map_location, weights_only=False)
